kind: PersistentVolume
apiVersion: v1
metadata:
  name: geoserver-pv-volume
  labels:
    type: local
    app: geoserver
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geoserver-pv-claim
  labels:
    app: geoserver
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
