apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: spi-geoserver-superuser
spec:
  rules:
  - services: ["spi-geoserver.*"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-spi-geoserver-superuser
spec:
  subjects:
  - group: "SUP"
  roleRef:
    kind: ServiceRole
    name: "spi-geoserver-superuser"